ECommerce.WebUI/Models/CategoryListViewModel.cs
using App.Entities.Models;

namespace ECommerce.WebUI
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
        public int CurrentCategory { get; set; }
    }
}

ECommerce.WebUI/Models/ErrorViewModel.cs
namespace ECommerce.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ECommerce.WebUI/Models/ProductAddViewModel.cs
using App.Entities.Models;

namespace ECommerce.WebUI.Models
{
    public class ProductAddViewModel
    {
        public Product Product { get; set; }
        public List<Category> Categories { get; set; }
    }
}

ECommerce.WebUI/Models/ProductListViewModel.cs
using App.Entities.Models;

namespace ECommerce.WebUI
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; set; }
        public int CurrentCategory { get; set; }
        public int PageCount { get; set; }
        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public bool AZState { get; set; }
        public bool LHState { get; set; }
    }
}

ECommerce.WebUI/Models/StudentTest.cs
namespace ECommerce.WebUI.Models
{
    public class StudentTest
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    }
}

ECommerce.WebUI/Controllers/CategoryController.cs
using App.Business.Abstract;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.WebUI.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        // GET: CategoryController
        public IActionResult Index()
        {
            var categories = _categoryService.GetAll();
            return Ok(categories);
        }

    }
}

ECommerce.WebUI/Controllers/HomeController.cs
using ECommerce.WebUI.ExtentionMethods;
using ECommerce.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ECommerce.WebUI.Controllers
{
    public class HomeController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }

        //public string Index()
        //{

        //    HttpContext.Session.SetInt32("age", 25);
        //    HttpContext.Session.SetString("name", "John Johnlu");

        //    var student = new StudentTest
        //    {
        //        Id = 1,
        //        Name = "Leyla",
        //        Surname = "Aliyeva"
        //    };
        //    HttpContext.Session.SetObject("student", student);

        //    return "Session Created";
        //}

        //public string GetSession()
        //{
        //    return $"Age {HttpContext.Session.GetInt32("age")}"+
        //           $"Name {HttpContext.Session.GetString("name")}";
        //}

        //public string GetStudent()
        //{
        //    var item = HttpContext.Session.GetObject<StudentTest>("student");
        //    return $"{item.Id}  -  {item.Name}  -  {item.Surname}";
        //}


        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

ECommerce.WebUI/Controllers/ProductController.cs
using App.Business.Abstract;
using App.Entities.Models;
using ECommerce.WebUI.ExtentionMethods;
using ECommerce.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;

namespace ECommerce.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductService _productService;
        private ICategoryService _categoryService;
        private IStateService _stateService;

        public ProductController(IProductService productService, ICategoryService categoryService, IStateService stateService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _stateService = stateService;
        }

        public IActionResult Index(int page = 1, int category = 0, bool azState = false, bool lhState = false)
        {
            var url = HttpContext.Request.QueryString.ToString();
            var products = _productService.GetAllByCategory(category);
            int pageSize = 10;

            if (url.Contains("azState"))
                products = _productService.GetProductsAZ(products, _stateService.CurrentState);
            else if (url.Contains("lhState"))
                products = _productService.GetProductsByFilterLoworHigh(products, _stateService.CurrentLHState);

            _stateService.SetState(url);
            var model = new ProductListViewModel()
            {
                Products = products.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                CurrentCategory = category,
                PageCount = (int)Math.Ceiling(products.Count / (double)pageSize),
                PageSize = pageSize,
                CurrentPage = page,
                AZState = _stateService.CurrentState,
                LHState = _stateService.CurrentLHState
            };

            return View(model);
        }







        [HttpGet]
        public IActionResult Add()
        {
            var model = new ProductAddViewModel();
            model.Product = new Product();
            model.Categories = _categoryService.GetAll();
            return View(model);
        }
        [HttpPost]
        public IActionResult Add(ProductAddViewModel model)
        {
            _productService.Add(model.Product);
            return RedirectToAction("index");
        }
    }
}

ECommerce.WebUI/ViewComponents/CategoryListViewComponent.cs
using App.Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace ECommerce.WebUI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke()
        {
            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll(),
                CurrentCategory = Convert.ToInt32(HttpContext.Request.Query["category"])
            };
            return View(model);
        }
    }
}

ECommerce.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ECommerce.WebUI/Views/Product/Add.cshtml
@model ProductAddViewModel
<form asp-action="add" method="post">

    <div class="form-group">
        <label>Product Name</label>
        <input asp-for="Product.ProductName" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label>Unit Price</label>
        <input asp-for="Product.UnitPrice" type="number" class="form-control">
    </div>
    <div class="form-group">
        <label>Units In Stock</label>
        <input asp-for="Product.UnitsInStock" type="number" class="form-control">
    </div>
    <div class="form-group">
        <label for="exampleFormControlSelect1">Example select</label>
        <select asp-for="Product.CategoryId" class="form-control" id="exampleFormControlSelect1">
            @foreach (var c in Model.Categories)
            {
                <option value="@c.CategoryId">@c.CategoryName</option>
            }
        </select>
    </div>
    <div class="form-group">
        <button class="btn btn-primary" type="submit">Add Product</button>
    </div>
</form>

ECommerce.WebUI/Views/Product/Index.cshtml
@model ProductListViewModel

<p>
	<a href="/product/add" class="btn btn-outline-primary">Create New</a>
</p>

<table class="table">
	<thead>
		<tr>

			@if (@Model.AZState)
			{
				<th><a class="btn btn-outline-primary" href="/product/index?page=@Model.CurrentPage&category=@Model.CurrentCategory&azState=true">A to Z</a></th>
			}
			else
			{
				<th><a class="btn btn-outline-danger" href="/product/index?page=@Model.CurrentPage&category=@Model.CurrentCategory&azState=false">Z to A</a></th>
			}


			@if (@Model.LHState)
			{
				<th><a class="btn btn-outline-primary" href="/product/index?page=@Model.CurrentPage&category=@Model.CurrentCategory&lhState=true">Low to High</a></th>
			}
			else
			{
				<th><a class="btn btn-outline-danger" href="/product/index?page=@Model.CurrentPage&category=@Model.CurrentCategory&lhState=false">High to Low</a></th>
			}

		</tr>
		<tr>
			<th>ProductName</th>
			<th>UnitPrice</th>
			<th>UnitsInStock</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model.Products)
		{
			<tr>
				<td>
					@item.ProductName
				</td>
				<td>
					@item.UnitPrice
				</td>
				<td>
					@item.UnitsInStock
				</td>
				<td>
					<a class="btn btn-xs btn-success">Add To Cart</a>
				</td>
			</tr>
		}
	</tbody>
</table>

<product-list-pager current-category="@Model.CurrentCategory"
					current-page="@Model.CurrentPage"
					page-count="@Model.PageCount"
					page-size="@Model.PageSize">

</product-list-pager>

ECommerce.WebUI/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel
<section class="list-group">
    @foreach (var item in Model.Categories)
    {

        var css = "list-group-item";
        @if(item.CategoryId==Model.CurrentCategory){
            css += " active";
        }
        <a style="cursor:pointer;" href="/product/index?category=@item.CategoryId" class="@css">@item.CategoryName</a>
    }
</section>

ECommerce.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerce.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerce.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Step Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                @await Component.InvokeAsync("CategoryList")
            </div>
            <main role="main" class="pb-3 col-md-10">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ECommerce.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>